import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Banner from "@/Components/Banner";
import {Roboto} from 'next/font/google' 

const inter = Inter({ subsets: ["latin"] });
const roboto_init = Roboto ({
  subsets:["latin"],
  weight:['100','300','400'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_init.variable}>
        <Header/>
        <Banner />
        {children}</body>
    </html>
  );
}
